#!/bin/bash

mongodb_dirs=$(ls -d mongodb*)
dir_list=("$mongodb_dirs")

# NOTE: the order matters but this is the right one
for i in ${dir_list[@]}; do
	echo building $i;
	cd $i;
	cat build;
	. build;
	cd ..;
done
